version: '3.1'

services:

  web:
    image: 'HTTPD'
    ports:
      - '9090:80'

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc12322

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - db
    ports:
      - "8000:8000"
